version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    # volumes:
    #   - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - custom-network
  
  nodejs:
    build: 
      context: node
      dockerfile: Dockerfile.dockerfile
    container_name: nodejs
    tty: true
    networks:
      - custom-network
    depends_on:
      - mysql
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s node index.js
  
  nginx:
    build: 
      context: nginx
      dockerfile: Dockerfile.dockerfile
    container_name: nginx
    networks:
      - custom-network
    depends_on:
      - nodejs
    ports:
      - "8080:80"
  
networks:
  custom-network:
    driver: bridge
